### PR TITLE
:bug: Update tackle2-hub dependency

### PR DESCRIPTION
**Pull request by dymurray**
This updates the tackle2-hub dependency which fixes yaml/json encoding of the reports.

### CODE REVIEW

**Review by mansam — APPROVED** [review]
LGTM. Fixes out of sync yaml field tags between Hub and analyzer.

**Comment by shawn-hurley** [comment]
@dymurray @mansam, do you know why the integration test is still failing? I thought this was supposed to fix it? @aufi can you help me understand as well?

**Comment by dymurray** [comment]
@shawn-hurley this PR actually has no bearing on the failing tests. This PR *should* help get https://github.com/konveyor/go-konveyor-tests/pull/53 passing. This directly fixes an issue we are seeing around missing codesnips.

**Comment by shawn-hurley** [comment]
If I'm understanding then do you want me to button merge this?

**Comment by shawn-hurley** [comment]
Noting here that I am purposefully merging this to unblock the test update, which *should* help fix the failing tests. If we see oddness around marshal/unmarshal, we should come here to look.

**Pull request merged**
